### ISSUE TITLE
Create release build for sensitivity masking changes

### ISSUE THREAD

**Issue by nrjohnstone** [reproio/terraform-j2md#15]
Can someone cut a new release for the changes in April for masking sensitive data... The tool is unusable at the moment to post markdown to pull requests due to the risk of sensitive values being exposed

**Comment by YAMASHITAHiroki** [comment]
Sorry for the late release.
We just released v0.0.5 
https://github.com/reproio/terraform-j2md/releases/tag/v0.0.5
